export const TEAM = [
  {
    id: 1,
    name: 'Hanssens',
    role: 'Leader',
    initials: 'H',
    clients: 28,
    closedThisMonth: 5,
    pipelineValue: 86400,
    followUpsDue: 7,
    referrals: 4,
    contactsThisWeek: 12,
    lastActivity: 'Today',
  },
  {
    id: 2,
    name: 'Sarah Dupont',
    role: 'Sales Rep',
    initials: 'SD',
    clients: 19,
    closedThisMonth: 3,
    pipelineValue: 42000,
    followUpsDue: 4,
    referrals: 2,
    contactsThisWeek: 8,
    lastActivity: 'Today',
  },
  {
    id: 3,
    name: 'Maxime Claes',
    role: 'Energy Broker',
    initials: 'MC',
    clients: 23,
    closedThisMonth: 6,
    pipelineValue: 61500,
    followUpsDue: 2,
    referrals: 5,
    contactsThisWeek: 15,
    lastActivity: 'Today',
  },
  {
    id: 4,
    name: 'Julie Vermeersch',
    role: 'Sales Rep',
    initials: 'JV',
    clients: 14,
    closedThisMonth: 1,
    pipelineValue: 18200,
    followUpsDue: 9,
    referrals: 1,
    contactsThisWeek: 4,
    lastActivity: 'Yesterday',
  },
]
